### ISSUE TITLE
missing dependency on 1.9.2@osx-snowleopard 

### ISSUE THREAD

**Issue by cowboyd** [revans/Ti#21]
```
legolas:~ cowboyd$ rvm use 1.9.2
Using /Users/cowboyd/.rvm/gems/ruby-1.9.2-p180
legolas:~ cowboyd$ gem install ti
Fetching: guard-0.3.4.gem (100%)
Fetching: haml-3.0.25.gem (100%)
Fetching: guard-sass-0.0.6.gem (100%)
Fetching: guard-coffeescript-0.2.4.gem (100%)
Fetching: em-websocket-0.2.1.gem (100%)
Fetching: guard-livereload-0.1.11.gem (100%)
Fetching: rubyzip-0.9.4.gem (100%)
Fetching: childprocess-0.2.1.gem (100%)
Fetching: selenium-webdriver-2.4.0.gem (100%)
Fetching: jasmine-1.0.2.1.gem (100%)
Fetching: colored-1.2.gem (100%)
Fetching: ti-0.1.9.gem (100%)
Successfully installed guard-0.3.4
Successfully installed haml-3.0.25
Successfully installed guard-sass-0.0.6
Successfully installed guard-coffeescript-0.2.4
Successfully installed em-websocket-0.2.1
Successfully installed guard-livereload-0.1.11
Successfully installed rubyzip-0.9.4
Successfully installed childprocess-0.2.1
Successfully installed selenium-webdriver-2.4.0
Successfully installed jasmine-1.0.2.1
Successfully installed colored-1.2
Successfully installed ti-0.1.9
12 gems installed
Installing ri documentation for guard-0.3.4...
Building YARD (yri) index for guard-0.3.4...
Installing ri documentation for haml-3.0.25...
Building YARD (yri) index for haml-3.0.25...
Installing ri documentation for guard-sass-0.0.6...
Building YARD (yri) index for guard-sass-0.0.6...
Installing ri documentation for guard-coffeescript-0.2.4...
Building YARD (yri) index for guard-coffeescript-0.2.4...
Installing ri documentation for em-websocket-0.2.1...
Building YARD (yri) index for em-websocket-0.2.1...
Building YARD (yri) index for guard-livereload-0.1.11...
Building YARD (yri) index for childprocess-0.2.1...
Installing ri documentation for selenium-webdriver-2.4.0...
Building YARD (yri) index for selenium-webdriver-2.4.0...
Installing ri documentation for jasmine-1.0.2.1...
Building YARD (yri) index for jasmine-1.0.2.1...
Installing ri documentation for colored-1.2...
Building YARD (yri) index for colored-1.2...
Building YARD (yri) index for ti-0.1.9...
Installing RDoc documentation for guard-0.3.4...
Installing RDoc documentation for haml-3.0.25...
Installing RDoc documentation for guard-sass-0.0.6...
Installing RDoc documentation for guard-coffeescript-0.2.4...
Installing RDoc documentation for em-websocket-0.2.1...
Installing RDoc documentation for selenium-webdriver-2.4.0...
Installing RDoc documentation for jasmine-1.0.2.1...
Installing RDoc documentation for colored-1.2...
legolas:~ cowboyd$ ti -h
/Users/cowboyd/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require': no such file to load -- rocco (LoadError)
    from /Users/cowboyd/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
    from /Users/cowboyd/.rvm/gems/ruby-1.9.2-p180/gems/ti-0.1.9/lib/ti.rb:8:in `<top (required)>'
    from /Users/cowboyd/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
    from /Users/cowboyd/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:54:in `require'
    from /Users/cowboyd/.rvm/gems/ruby-1.9.2-p180/gems/ti-0.1.9/bin/ti:3:in `<top (required)>'
    from /Users/cowboyd/.rvm/gems/ruby-1.9.2-p180/bin/ti:19:in `load'
    from /Users/cowboyd/.rvm/gems/ruby-1.9.2-p180/bin/ti:19:in `<main>'
```

**Comment by baldrailers** [comment]
Let me update that part. I think the quick fix for that one will be install the gem:

`gem install rocco`

Thanks and will come back to you once I have the fix.

**Comment by cowboyd** [comment]
yep, just wanted to give you a heads up. cheers!

**Comment by baldrailers** [comment]
Updated the latest codes to include the missing dependencies. Thanks!
