### ISSUE TITLE
Cannot run rake or ti compile/build

### ISSUE THREAD

**Issue by michael4reynolds** [revans/Ti#35]
When trying to rake the sample project this is what I receive:

Mike-Rs-MacBook-Pro:HelloTi mikemac$ rake
Compiling CoffeeScript
Successfully compiled CoffeeScript
Compiling stylesheets
Building with Titanium... (DEVICE_TYPE: iphone)
bash -c "~/Library/Application\ Support/Titanium/mobilesdk/osx/1.8.2/iphone/builder.py run /Users/mikemac/Documents/Titanium Studio Workspace/HelloTi/ 5.0 com.yourdomain.helloti HelloTi iphone " | perl -pe 's/^[DEBUG]._$/\e[35m$&\e[0m/g;s/^[INFO]._$/\e[36m$&\e[0m/g;s/^[WARN]._$/\e[33m$&\e[0m/g;s/^[ERROR]._$/\e[31m$&\e[0m/g;'
[INFO] One moment, building ...
Traceback (most recent call last):
  File "/Users/mikemac/Library/Application Support/Titanium/mobilesdk/osx/1.8.2/iphone/builder.py", line 1545, in <module>
    main(sys.argv)
  File "/Users/mikemac/Library/Application Support/Titanium/mobilesdk/osx/1.8.2/iphone/builder.py", line 632, in main
    ti = TiAppXML(tiapp_xml)
  File "/Users/mikemac/Library/Application Support/Titanium/mobilesdk/osx/1.8.2/iphone/../tiapp.py", line 52, in **init**
    data = codecs.open(self.file,'r','utf-8','replace')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 881, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/Users/mikemac/Documents/Titanium/tiapp.xml'

**Comment by michael4reynolds** [comment]
Fixed the issue by editing the config.rb file and removing any spaces from any of the folder names.

**Comment by jaredmoody** [comment]
This should be re-opened. The build process should not fail because there's a space in a directory name in the path to the project.
